---
- name: Inspect Execution Environment
  hosts: localhost
  gather_facts: false
  tasks:
    - name: List installed Ansible collections
      ansible.builtin.command: ansible-galaxy collection list
      register: galaxy_out

    - name: Show installed collections
      debug:
        var: galaxy_out.stdout_lines

- name: Run read-only command on switch
  hosts: all
  gather_facts: no
  tasks:
    - name: Run show version
      cisco.ios.ios_command:
        commands: show version
      register: output

    - name: Display output
      debug:
        var: output.stdout_lines

