---
- name: Inspect Execution Environment
  hosts: localhost
  gather_facts: false
  tasks:
    - debug:
        msg: "testing"
    #- name: List installed Ansible collections
    #  ansible.builtin.command: ansible-galaxy collection list
    #  register: galaxy_out

    #- name: Show installed collections
    #  debug:
    #    var: galaxy_out.stdout_lines