---
- name: Run read-only command on switch
  hosts: all
  gather_facts: no
  tasks:
    - name: Run show version
      cisco.ios.ios_command:
        commands: show version
      register: output

    - name: Display output
      debug:
        var: output.stdout_lines

- name: List installed Ansible collections
  ansible.builtin.command: ansible-galaxy collection List
  register: galaxy_out
  debug:
    var: galaxy_out.stdout_lines